version: "3.7"

# To run:
# export IMAGE_TAG=sal_3.10.0-4.2.0_salobj_4.5.0
# docker-compose build salbase
#  or to build all
# docker-compose build salbase salrpm salsrc salobj

services:
  salbase:
    image: lsstdm/salbase:${IMAGE_TAG}
    build:
      context: ./salbase
      labels:
        com.description: "LSST DDS/SAL base docker image."

  salrpm:
    image: lsstdm/salrpm:${IMAGE_TAG}
    depends_on:
      - salbase
    build:
      context: ./salrpm
      labels:
        com.description: "Docker OpenSplice/SAL image rpms"
      args:
        salbase_image : lsstdm/salbase:${IMAGE_TAG}
        SAL_VERSION : "3.10.0-4.2.0.el7"
        OSPL_VERSION : "6.9.0"

  salsrc:
    image: lsstdm/salsrc:${IMAGE_TAG}
    depends_on:
      - salrpm
    build:
      context: ./salsrc
      labels:
        com.description: "Docker OpenSplice/SAL image from source"
      args:
        salrpm_image: lsstdm/salrpm:${IMAGE_TAG}
        TS_SAL_VERSION : "v3.10.0"
        TS_XML_VERSION : "v4.2.0"
        INSTALL_PATH : "/opt/lsst"

  salobj:
    image: lsstdm/salobj:${IMAGE_TAG}
    depends_on:
      - salsrc
    build:
      context: ./salobj
      labels:
        com.description: "Docker inage for ts_salobj"
      args:
        salsrc_image : lsstdm/salsrc:${IMAGE_TAG}
        TS_SALOBJ_VERSION : "v4.5.0"
        TS_IDL_VERSION: "v0.2.0"
        INSTALL_PATH : "/opt/lsst"
        GIT_LSST_TS: "https://github.com/lsst-ts"
        REPOS_TMP: "/tmp/repos"
