# docker-compose version of this compose file
version: "3.7"

# To run:
#export OSPL_VERSION=6.9.0
#export LSSTTS_SAL_VERSION=4.0.0
#export LSSTTS_SALOBJ_VERSION=5.4.0
#export LSSTTS_XML_VERSION=4.7.0
#export LSSTTS_IDL_VERSION=1.1.0
#export HEADERSERVICE_VERSION=1.4.0
#export MINICONDA_PATH=/opt/miniconda3
#export TAG=v${HEADERSERVICE_VERSION}_salobj_v${LSSTTS_SALOBJ_VERSION}_xml_v${LSSTTS_XML_VERSION}
#export CCS_IDL_LIST="EFD ATHeaderService ATCamera ATArchiver ATPtg ATMCS ATSpectrograph ATTCS ATHexapod CCCamera CCHeaderService"
#docker-compose build salrun salidl salobj headerservice


services:
  salrun:
    image: lsstdm/salrun:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}-salobj_${LSSTTS_SALOBJ_VERSION}

    build:
      context: ./salrun
      args:
        - OSPL_VERSION
        - OSPL_RPM_VERSION
        - LSSTTS_DDS_VERSION
        - LSSTTS_DDSCONFIG_VERSION
        - MINICONDA_PATH
        - NEXUS_USER
        - NEXUS_PASS
        - LSSTTS_IDL_VERSION
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION

  salidl:
    image: lsstdm/salidl:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}
    build:
      context: ./salidl
      args:
        - OSPL_VERSION
        - LSSTTS_IDL_VERSION
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
        - MINICONDA_PATH
    depends_on:
      - salrun

  salobj:
    image: lsstdm/salobj:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}-salobj_${LSSTTS_SALOBJ_VERSION}
    build:
      context: ./salobj
      args:
        - LSSTTS_SALOBJ_VERSION
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
        - MINICONDA_PATH
    depends_on:
      - salidl

  salsrc:
    image: lsstdm/salsrc:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}
    build:
      context: ./salsrc
      args:
        - OSPL_VERSION
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
        - CCS_IDL_LIST
    depends_on:
      - salrun


  headerservice:
    image: lsstdm/headerservice:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}-salobj_${LSSTTS_SALOBJ_VERSION}-hs_${HEADERSERVICE_VERSION}
    build:
      context: ./headerservice
      args:
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
        - LSSTTS_SALOBJ_VERSION
        - HEADERSERVICE_VERSION
        - MINICONDA_PATH
    depends_on:
      - salobj

  atarchiver:
    image: lsstdm/atarchiver:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}
    build:
      context: ./atarchiver
      args:
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
    depends_on:
      - salidl
