# docker-compose version of this compose file
version: "3.7"

# To run:
# export OSPL_VERSION=6.9.0
# export LSSTTS_SAL_VERSION=3.10.0
# export LSSTTS_SALOBJ_VERSION=4.5.0
# export LSSTTS_XML_VERSION=4.2.0
# export LSSTTS_IDL_VERSION=0.2.0

services:
  salrun:
    image: lsstdm/salrun:${OSPL_VERSION}
    build:
      context: ./salrun
      args:
        - OSPL_VERSION

  salobj:
    image: lsstdm/salobj:${LSSTTS_SALOBJ_VERSION}
    build:
      context: ./salobj
      args:
        - OSPL_VERSION
        - LSSTTS_SALOBJ_VERSION
    depends_on:
      - salrun

  salidl:
    image: lsstdm/salidl:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}
    build:
      context: ./salidl
      args:
        - OSPL_VERSION
        - LSSTTS_SALOBJ_VERSION
        - LSSTTS_IDL_VERSION
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
    depends_on:
      - salobj

  atarchiver:
    image: lsstdm/atarchiver:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}
    build:
      context: ./atarchiver
      args:
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
    depends_on:
      - salidl

  atheaderservice:
    image: lsstdm/atheaderservice:${LSSTTS_SAL_VERSION}-${LSSTTS_XML_VERSION}
    build:
      context: ./atheaderservice
      args:
        - LSSTTS_SAL_VERSION
        - LSSTTS_XML_VERSION
    depends_on:
      - salidl
